; Listing generated by Microsoft (R) Optimizing Compiler Version 19.39.33523.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__FE09AF47_concurrencysal@h DB 01H
__C073CA79_sal@h DB 01H
__D6AFE870_vadefs@h DB 01H
__D63E96CF_vcruntime@h DB 01H
__32E3D3D2_xkeycheck@h DB 01H
__CFD6EDFA_yvals_core@h DB 01H
__10D4A829_limits@h DB 01H
__9CD02892_climits DB 01H
__1B0272D9_corecrt@h DB 01H
__A3D3E4E8_vcruntime_new@h DB 01H
__8D1A214D_vcruntime_new_debug@h DB 01H
__935DC21B_crtdbg@h DB 01H
__497BC13E_crtdefs@h DB 01H
__DDE8D0E0_use_ansi@h DB 01H
__AE7FBCDF_yvals@h DB 01H
__BB16330F_corecrt_math@h DB 01H
__3BF2A406_math@h DB 01H
__45DED006_corecrt_malloc@h DB 01H
__13F5961F_stddef@h DB 01H
__FD6DBD68_corecrt_search@h DB 01H
__E2E33A61_corecrt_wstdlib@h DB 01H
__6E5ACABA_stdlib@h DB 01H
__183F0A60_cstdlib DB 01H
__26E6E2A9_xtr1common DB 01H
__F5A7E1DF_intrin0@inl@h DB 01H
__50567835_intrin0@h DB 01H
__A2C9C4CE_cmath DB 01H
__44420885_corecrt_stdio_config@h DB 01H
__AB601D8D_corecrt_wstdio@h DB 01H
__C1EC35D3_stdio@h DB 01H
__1C5946C5_cstdio DB 01H
__61CC25A1_errno@h DB 01H
__3EADF068_vcruntime_string@h DB 01H
__E4C945B4_corecrt_memcpy_s@h DB 01H
__8EAFF484_corecrt_memory@h DB 01H
__6490AEC5_corecrt_wstring@h DB 01H
__E8295E1E_string@h DB 01H
__54ADA280_cstring DB 01H
__EF1F6BBA_corecrt_wconio@h DB 01H
__74484FB3_corecrt_wctype@h DB 01H
__3D1D430C_corecrt_wdirect@h DB 01H
__8ECB7138_corecrt_share@h DB 01H
__DB7FEBA6_corecrt_wio@h DB 01H
__9A9F0068_corecrt_wprocess@h DB 01H
__369A9BC3_corecrt_wtime@h DB 01H
__CE789B9D_types@h DB 01H
__9901C817_stat@h DB 01H
__3FCAD62E_wchar@h DB 01H
__86D29096_cwchar DB 01H
__C51215A0_iosfwd DB 01H
__BDF4D0CD_cstddef DB 01H
__E4CFD974_initializer_list DB 01H
__AEA28616_stdint@h DB 01H
__A561EB1D_cstdint DB 01H
__7C4A1519_type_traits DB 01H
__2F328FEB_utility DB 01H
__91F58E7E___msvc_iter_core@hpp DB 01H
__C27AFEEB_xutility DB 01H
__D3D649AB_iterator DB 01H
__F7972D0B_share@h DB 01H
__F338F6F9___msvc_system_error_abi@hpp DB 01H
__8178323E_cerrno DB 01H
__FA77ED4C_malloc@h DB 01H
__89766DA4_corecrt_terminate@h DB 01H
__EEF52EF9_eh@h DB 01H
__85F4241F_vcruntime_exception@h DB 01H
__8124AFA8_exception DB 01H
__BE6CFB00___msvc_sanitizer_annotate_container@hpp DB 01H
__B9985323_float@h DB 01H
__6F1D8D42_cfloat DB 01H
__09FBC026_limits DB 01H
__5003AD96_new DB 01H
__8B28237E_xatomic@h DB 01H
__45A7EC28_xmemory DB 01H
__31746AB4_xstring DB 01H
__086A95F5_stdexcept DB 01H
__8C4E33AA_xcall_once@h DB 01H
__06EAA9D0_xerrc@h DB 01H
__0A9237D2_time@h DB 01H
__647A58C6_ctime DB 01H
__74BE1DAA_xtimec@h DB 01H
__BCA6E753_xthreads@h DB 01H
__62CE9CE4_atomic DB 01H
__3313218A_system_error DB 01H
__851B68E1_vcruntime_typeinfo@h DB 01H
__B2A50DF2_typeinfo DB 01H
__B555CCA8_memory DB 01H
__99109BA7_xfacet DB 01H
__F99E20B2___msvc_xlocinfo_types@hpp DB 01H
__1EC467ED_ctype@h DB 01H
__1392A162_cctype DB 01H
__791C33B7_locale@h DB 01H
__8B93D6B1_clocale DB 01H
__AD2CEE3A_xlocinfo DB 01H
__EE4A1E85_xlocale DB 01H
__94C99929_xiosbase DB 01H
__0ACA2D49_streambuf DB 01H
__70CD7892_xlocnum DB 01H
__A8CE9780_ios DB 01H
__FD5AC441_ostream DB 01H
__9E8AF17B_istream DB 01H
__A00384F4_iostream DB 01H
__9E378DB7_DotProduct@h DB 01H
__4BE2BEFE_DotProduct@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	?DotProduct@@YAHQEAH0HH@Z			; DotProduct
PUBLIC	__JustMyCode_Default
EXTRN	__CheckForDebuggerJustMyCode:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX@Z DD imagerel $LN3
	DD	imagerel $LN3+33
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX_K@Z DD imagerel $LN3
	DD	imagerel $LN3+38
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?DotProduct@@YAHQEAH0HH@Z DD imagerel $LN6
	DD	imagerel $LN6+112
	DD	imagerel $unwind$?DotProduct@@YAHQEAH0HH@Z
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?DotProduct@@YAHQEAH0HH@Z DD 025031e01H
	DD	0d219231eH
	DD	05015H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX_K@Z DD 025031401H
	DD	0b20f2314H
	DD	0500bH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX@Z DD 025030f01H
	DD	0b20a230fH
	DD	05006H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
; File C:\Users\Allan\OneDrive\Desktop\Coding\C++\CSC342_TakeHome_DotProduct\DotProduct.cpp
;	COMDAT ?DotProduct@@YAHQEAH0HH@Z
_TEXT	SEGMENT
i$1 = 0
A$ = 96
B$ = 104
C$ = 112
size$ = 120
?DotProduct@@YAHQEAH0HH@Z PROC				; DotProduct, COMDAT

; 7    : int DotProduct(int A[] ,int B[], int C, int size){

$LN6:
	mov	DWORD PTR [rsp+32], r9d
	mov	DWORD PTR [rsp+24], r8d
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	sub	rsp, 112				; 00000070H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__4BE2BEFE_DotProduct@cpp
	call	__CheckForDebuggerJustMyCode

; 8    :     for(int i =0;i<size;i++){

	mov	DWORD PTR i$1[rbp], 0  ; change to mov eax, 0 REMOVED
	; NEW ADDED ASM 
	; mov eax, 0
	;mov	rdx, QWORD PTR A$[rbp]
	;mov	r8, QWORD PTR B$[rbp]
	;mov	ecx, DWORD PTR C$[rbp]
	;mov	edx, DWORD PTR size$[rbp]
	jmp	SHORT $LN4@DotProduct 
$LN2@DotProduct:
	mov	eax, DWORD PTR i$1[rbp] ; remove this so i is not in stack REMOVE
	inc	eax
	mov	DWORD PTR i$1[rbp], eax ; again remove we this REMOVE
$LN4@DotProduct:
	mov	eax, DWORD PTR size$[rbp] ; replace eax with edx and add to initlztion
	
	cmp	DWORD PTR i$1[rbp], eax	; cmp eax, edx REMOVE
	;cmp eax,edx
	jge	SHORT $LN3@DotProduct

; 9    :         C = C +A[i]*B[i];

	movsxd	rax, DWORD PTR i$1[rbp] ;replace Dword ptr i$1 with eax REMOVE
	movsxd	rcx, DWORD PTR i$1[rbp] ;remove as it is already rax  REMOVE
	;movsxd rax, eax 
	mov	rdx, QWORD PTR A$[rbp] ;REMOVE
	mov	r8, QWORD PTR B$[rbp]; REMOVE
	mov	eax, DWORD PTR [rdx+rax*4] ;REMOVE change eax to esi
	;mov esi, DWORD PTR [rdx+rax*4]
	imul	eax, DWORD PTR [r8+rcx*4] ; REMOVE change eax to esi  and change it too rax*4
	;imul esi, DWORD PTR [r8+rax*4]
	mov	ecx, DWORD PTR C$[rbp] ;REMOVE move to initalization
	; take all rdx, r8, ecx into the inilaize part 
	add	ecx, eax ;REMOVE add ecx,edi 
	;add ecx,edi 
	mov	eax, ecx ;REMOVE mov edi,ecx 
	;mov edi,ecx 
	mov	DWORD PTR C$[rbp], eax ;REMOVE  eax, to edi 
	;mov	DWORD PTR C$[rbp], edi 
; 10   :     }
	
	jmp	SHORT $LN2@DotProduct
$LN3@DotProduct:

; 11   :     return C;

	mov	eax, DWORD PTR C$[rbp]

; 12   : } 

	lea	rsp, QWORD PTR [rbp+80]
	pop	rbp
	ret	0
?DotProduct@@YAHQEAH0HH@Z ENDP				; DotProduct
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
; File C:\Users\Allan\OneDrive\Desktop\Coding\C++\CSC342_TakeHome_DotProduct\DotProduct.cpp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 80
__formal$ = 88
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT

$LN3:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	sub	rsp, 96					; 00000060H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__4BE2BEFE_DotProduct@cpp
	call	__CheckForDebuggerJustMyCode
	lea	rsp, QWORD PTR [rbp+64]
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
; File C:\Users\Allan\OneDrive\Desktop\Coding\C++\CSC342_TakeHome_DotProduct\DotProduct.cpp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 80
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT

$LN3:
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	sub	rsp, 96					; 00000060H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__4BE2BEFE_DotProduct@cpp
	call	__CheckForDebuggerJustMyCode
	lea	rsp, QWORD PTR [rbp+64]
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
